CC = i686-w64-mingw32-gcc
CXX = i686-w64-mingw32-c++
WINDRES = i686-w64-mingw32-windres
CFLAGS = -std=c99 -Wall -Wextra -mwindows -Os
LDFLAGS = -luser32 -lcomctl32 -lshell32 -lversion -static

all: out/bootstrap32.exe

out/bootstrap32.exe: out/setup.o out/setup.res.o
	$(CC) $(CFLAGS) -o $@ $^ $(LDFLAGS)

out/setup.o: setup.c
	$(CC) $(CFLAGS) -c -o $@ $<

out/setup.res.o: setup.rc setup.manifest setup.ico
	$(WINDRES) -O coff -o $@ $<

clean:
	rm -rf out/*.o out/*.exe out/*.c out/*.h

